version: '3.4'
services:
  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    ports:
      - 27017:27017
    networks:
      - forge_network
    volumes:
      - mongodb:/var/lib/mongodb
  agile-tools-backend:
    image: agile-tools-backend
    container_name: agile-tools-backend
    ports:
      - 1337:1337
    networks:
      - forge_network
    depends_on:
      - mongodb
    environment:
      VIRTUAL_HOST: agile-tools-api.forge.labsii.loc
      MONGODB_URI: mongodb://mongodb:27017/dev
      APP_ID: mongodb://mongodb:27017/dev
  agile-tools-frontend:
    image: agile-tools-frontend
    container_name: agile-tools-frontend
    ports:
      - 8088:8080
    networks:
      - forge_network
    environment:
      VIRTUAL_HOST: agile-tools.forge.labsii.loc

networks:
  forge_network:
    external: true

volumes:
  mongodb:
